ALTER TABLE url_fields
    ADD id INTEGER GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE url_fields
    ADD required BOOLEAN;

ALTER TABLE url_fields
    ALTER COLUMN required SET NOT NULL;

ALTER TABLE url_fields
    ADD CONSTRAINT pk_url_fields PRIMARY KEY (id);

ALTER TABLE fields
    DROP COLUMN required;

ALTER TABLE url_fields
    ALTER COLUMN field_id DROP NOT NULL;

ALTER TABLE url_fields
    ALTER COLUMN url_id DROP NOT NULL;