create table answers
(
    answer_number integer   not null,
    assignment_id integer,
    id            integer generated by default as identity,
    is_correct    boolean   not null,
    result        float(53) not null,
    answer        varchar(255),
    primary key (id)
);
create table assignments
(
    attempts_remaining integer not null,
    function_id        integer,
    has_correct_answer boolean not null,
    id                 integer generated by default as identity,
    status             smallint check (status between 0 and 4),
    user_assigned_id   integer,
    primary key (id)
);
create table functions
(
    id              integer generated by default as identity,
    result_type     smallint check (result_type between 0 and 1),
    topic_id        integer,
    variables_count integer,
    hint            varchar(255),
    max_value       varchar(255),
    min_value       varchar(255),
    text            varchar(255),
    primary key (id)
);
create table groups
(
    id   integer generated by default as identity,
    name varchar(255),
    primary key (id)
);
create table marks
(
    assignment_id integer,
    id            integer generated by default as identity,
    mark          integer not null,
    comment       varchar(255),
    primary key (id)
);
create table roles
(
    id   integer generated by default as identity,
    name varchar(255) check (name in ('STUDENT', 'TEACHER', 'ADMIN')),
    primary key (id)
);
create table topics
(
    id   integer generated by default as identity,
    name varchar(255),
    primary key (id)
);
create table user_info
(
    group_id   integer,
    id         integer not null,
    first_name varchar(255),
    last_name  varchar(255),
    primary key (id)
);
create table user_roles
(
    role_id integer not null,
    user_id integer not null
);
create table users
(
    group_id              integer,
    id                    integer generated by default as identity,
    is_approved           boolean,
    email                 varchar(255),
    forgot_password_token varchar(255),
    password              varchar(255),
    refresh_token         varchar(255),
    primary key (id)
);
alter table if exists answers
    add constraint FKgjkcqybs0a3akukb2h46s5hmf foreign key (assignment_id) references assignments;
alter table if exists assignments
    add constraint FK78gs4tabc11nl9vhagk0w38dl foreign key (function_id) references functions;
alter table if exists assignments
    add constraint FKbwmd4hu3ilm5bnvxwu1hpq857 foreign key (user_assigned_id) references users;
alter table if exists functions
    add constraint FKkeu713mny1w38bcqwaypk5v0w foreign key (topic_id) references topics;
alter table if exists marks
    add constraint FKfb1jnc1s7y4idxwfu1mgdarmh foreign key (assignment_id) references assignments;
alter table if exists user_info
    add constraint FKr4gogbvxc9a4i6gdg6c7lyrma foreign key (group_id) references groups;
alter table if exists user_info
    add constraint FK84m4x29g16h6ll9apisavaqow foreign key (id) references users;
alter table if exists user_roles
    add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles;
alter table if exists user_roles
    add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users;
alter table if exists users
    add constraint FKemfuglprp85bh5xwhfm898ysc foreign key (group_id) references groups;create table answers (answer_number integer not null, assignment_id integer, id integer generated by default as identity, is_correct boolean not null, result float(53) not null, answer varchar(255), primary key (id));
create table assignments (attempts_remaining integer not null, function_id integer, has_correct_answer boolean not null, id integer generated by default as identity, status smallint check (status between 0 and 2), user_assigned_id integer, primary key (id));
create table functions (id integer generated by default as identity, result_type smallint check (result_type between 0 and 1), topic_id integer, variables_count integer, hint varchar(255), max_value varchar(255), min_value varchar(255), text varchar(255), primary key (id));
create table groups (id integer generated by default as identity, name varchar(255), primary key (id));
create table marks (assignment_id integer, id integer generated by default as identity, mark integer not null, comment varchar(255), primary key (id));
create table roles (id integer generated by default as identity, name varchar(255) check (name in ('STUDENT','TEACHER','ADMIN')), primary key (id));
create table topics (id integer generated by default as identity, name varchar(255), primary key (id));
create table user_info (group_id integer, id integer not null, first_name varchar(255), last_name varchar(255), primary key (id));
create table user_roles (role_id integer not null, user_id integer not null);
create table users (id integer generated by default as identity, is_approved boolean, email varchar(255), forgot_password_token varchar(255), password varchar(255), refresh_token varchar(255), primary key (id));
alter table if exists answers add constraint FKgjkcqybs0a3akukb2h46s5hmf foreign key (assignment_id) references assignments;
alter table if exists assignments add constraint FK78gs4tabc11nl9vhagk0w38dl foreign key (function_id) references functions;
alter table if exists assignments add constraint FKbwmd4hu3ilm5bnvxwu1hpq857 foreign key (user_assigned_id) references users;
alter table if exists functions add constraint FKkeu713mny1w38bcqwaypk5v0w foreign key (topic_id) references topics;
alter table if exists marks add constraint FKfb1jnc1s7y4idxwfu1mgdarmh foreign key (assignment_id) references assignments;
alter table if exists user_info add constraint FKr4gogbvxc9a4i6gdg6c7lyrma foreign key (group_id) references groups;
alter table if exists user_info add constraint FK84m4x29g16h6ll9apisavaqow foreign key (id) references users;
alter table if exists user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles;
alter table if exists user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users;
create table answers (answer_number integer not null, assignment_id integer, id integer generated by default as identity, is_correct boolean not null, result float(53) not null, answer varchar(255), primary key (id));
create table assignments (attempts_remaining integer not null, function_id integer, has_correct_answer boolean not null, id integer generated by default as identity, status smallint check (status between 0 and 2), user_assigned_id integer, primary key (id));
create table functions (id integer generated by default as identity, result_type smallint check (result_type between 0 and 1), topic_id integer, variables_count integer, hint varchar(255), max_value varchar(255), min_value varchar(255), text varchar(255), primary key (id));
create table groups (id integer generated by default as identity, name varchar(255), primary key (id));
create table marks (assignment_id integer, id integer generated by default as identity, mark integer not null, comment varchar(255), primary key (id));
create table roles (id integer generated by default as identity, name varchar(255) check (name in ('STUDENT','TEACHER','ADMIN')), primary key (id));
create table topics (id integer generated by default as identity, name varchar(255), primary key (id));
create table user_info (group_id integer, id integer not null, first_name varchar(255), last_name varchar(255), primary key (id));
create table user_roles (role_id integer not null, user_id integer not null);
create table users (id integer generated by default as identity, is_approved boolean, email varchar(255), forgot_password_token varchar(255), password varchar(255), refresh_token varchar(255), primary key (id));
alter table if exists answers add constraint FKgjkcqybs0a3akukb2h46s5hmf foreign key (assignment_id) references assignments;
alter table if exists assignments add constraint FK78gs4tabc11nl9vhagk0w38dl foreign key (function_id) references functions;
alter table if exists assignments add constraint FKbwmd4hu3ilm5bnvxwu1hpq857 foreign key (user_assigned_id) references users;
alter table if exists functions add constraint FKkeu713mny1w38bcqwaypk5v0w foreign key (topic_id) references topics;
alter table if exists marks add constraint FKfb1jnc1s7y4idxwfu1mgdarmh foreign key (assignment_id) references assignments;
alter table if exists user_info add constraint FKr4gogbvxc9a4i6gdg6c7lyrma foreign key (group_id) references groups;
alter table if exists user_info add constraint FK84m4x29g16h6ll9apisavaqow foreign key (id) references users;
alter table if exists user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles;
alter table if exists user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users;
create table answers (answer_number integer not null, assignment_id integer, id integer generated by default as identity, is_correct boolean not null, result float(53) not null, answer varchar(255), primary key (id));
create table assignments (attempts_remaining integer not null, function_id integer, has_correct_answer boolean not null, id integer generated by default as identity, status smallint check (status between 0 and 2), user_assigned_id integer, primary key (id));
create table functions (id integer generated by default as identity, result_type smallint check (result_type between 0 and 1), topic_id integer, variables_count integer, hint varchar(255), max_value varchar(255), min_value varchar(255), text varchar(255), primary key (id));
create table groups (id integer generated by default as identity, name varchar(255), primary key (id));
create table marks (assignment_id integer, id integer generated by default as identity, mark integer not null, comment varchar(255), primary key (id));
create table roles (id integer generated by default as identity, name varchar(255) check (name in ('STUDENT','TEACHER','ADMIN')), primary key (id));
create table topics (id integer generated by default as identity, name varchar(255), primary key (id));
create table user_info (group_id integer, id integer not null, first_name varchar(255), last_name varchar(255), primary key (id));
create table user_roles (role_id integer not null, user_id integer not null);
create table users (id integer generated by default as identity, is_approved boolean, email varchar(255), forgot_password_token varchar(255), password varchar(255), refresh_token varchar(255), primary key (id));
alter table if exists answers add constraint FKgjkcqybs0a3akukb2h46s5hmf foreign key (assignment_id) references assignments;
alter table if exists assignments add constraint FK78gs4tabc11nl9vhagk0w38dl foreign key (function_id) references functions;
alter table if exists assignments add constraint FKbwmd4hu3ilm5bnvxwu1hpq857 foreign key (user_assigned_id) references users;
alter table if exists functions add constraint FKkeu713mny1w38bcqwaypk5v0w foreign key (topic_id) references topics;
alter table if exists marks add constraint FKfb1jnc1s7y4idxwfu1mgdarmh foreign key (assignment_id) references assignments;
alter table if exists user_info add constraint FKr4gogbvxc9a4i6gdg6c7lyrma foreign key (group_id) references groups;
alter table if exists user_info add constraint FK84m4x29g16h6ll9apisavaqow foreign key (id) references users;
alter table if exists user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles;
alter table if exists user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users;
create table answers (answer_number integer not null, assignment_id integer, id integer generated by default as identity, is_correct boolean not null, result float(53) not null, answer varchar(255), primary key (id));
create table assignments (attempts_remaining integer not null, function_id integer, has_correct_answer boolean not null, id integer generated by default as identity, status smallint check (status between 0 and 2), user_assigned_id integer, primary key (id));
create table functions (id integer generated by default as identity, result_type smallint check (result_type between 0 and 1), topic_id integer, variables_count integer, hint varchar(255), max_value varchar(255), min_value varchar(255), text varchar(255), primary key (id));
create table groups (id integer generated by default as identity, name varchar(255), primary key (id));
create table marks (assignment_id integer, id integer generated by default as identity, mark integer not null, comment varchar(255), primary key (id));
create table roles (id integer generated by default as identity, name varchar(255) check (name in ('STUDENT','TEACHER','ADMIN')), primary key (id));
create table topics (id integer generated by default as identity, name varchar(255), primary key (id));
create table user_info (group_id integer, id integer not null, first_name varchar(255), last_name varchar(255), primary key (id));
create table user_roles (role_id integer not null, user_id integer not null);
create table users (id integer generated by default as identity, is_approved boolean, email varchar(255), forgot_password_token varchar(255), password varchar(255), refresh_token varchar(255), primary key (id));
alter table if exists answers add constraint FKgjkcqybs0a3akukb2h46s5hmf foreign key (assignment_id) references assignments;
alter table if exists assignments add constraint FK78gs4tabc11nl9vhagk0w38dl foreign key (function_id) references functions;
alter table if exists assignments add constraint FKbwmd4hu3ilm5bnvxwu1hpq857 foreign key (user_assigned_id) references users;
alter table if exists functions add constraint FKkeu713mny1w38bcqwaypk5v0w foreign key (topic_id) references topics;
alter table if exists marks add constraint FKfb1jnc1s7y4idxwfu1mgdarmh foreign key (assignment_id) references assignments;
alter table if exists user_info add constraint FKr4gogbvxc9a4i6gdg6c7lyrma foreign key (group_id) references groups;
alter table if exists user_info add constraint FK84m4x29g16h6ll9apisavaqow foreign key (id) references users;
alter table if exists user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles;
alter table if exists user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users;
create table answers (answer_number integer not null, assignment_id integer, id integer generated by default as identity, is_correct boolean not null, result float(53) not null, answer varchar(255), primary key (id));
create table assignments (attempts_remaining integer not null, function_id integer, has_correct_answer boolean not null, id integer generated by default as identity, status smallint check (status between 0 and 2), user_assigned_id integer, primary key (id));
create table functions (id integer generated by default as identity, result_type smallint check (result_type between 0 and 1), topic_id integer, variables_count integer, hint varchar(255), max_value varchar(255), min_value varchar(255), text varchar(255), primary key (id));
create table groups (id integer generated by default as identity, name varchar(255), primary key (id));
create table marks (assignment_id integer, id integer generated by default as identity, mark integer not null, comment varchar(255), primary key (id));
create table roles (id integer generated by default as identity, name varchar(255) check (name in ('STUDENT','TEACHER','ADMIN')), primary key (id));
create table topics (id integer generated by default as identity, name varchar(255), primary key (id));
create table user_info (group_id integer, id integer not null, first_name varchar(255), last_name varchar(255), primary key (id));
create table user_roles (role_id integer not null, user_id integer not null);
create table users (id integer generated by default as identity, is_approved boolean, email varchar(255), forgot_password_token varchar(255), password varchar(255), refresh_token varchar(255), primary key (id));
alter table if exists answers add constraint FKgjkcqybs0a3akukb2h46s5hmf foreign key (assignment_id) references assignments;
alter table if exists assignments add constraint FK78gs4tabc11nl9vhagk0w38dl foreign key (function_id) references functions;
alter table if exists assignments add constraint FKbwmd4hu3ilm5bnvxwu1hpq857 foreign key (user_assigned_id) references users;
alter table if exists functions add constraint FKkeu713mny1w38bcqwaypk5v0w foreign key (topic_id) references topics;
alter table if exists marks add constraint FKfb1jnc1s7y4idxwfu1mgdarmh foreign key (assignment_id) references assignments;
alter table if exists user_info add constraint FKr4gogbvxc9a4i6gdg6c7lyrma foreign key (group_id) references groups;
alter table if exists user_info add constraint FK84m4x29g16h6ll9apisavaqow foreign key (id) references users;
alter table if exists user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles;
alter table if exists user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users;
create table answers (answer_number integer not null, assignment_id integer, id integer generated by default as identity, is_correct boolean not null, result float(53) not null, answer varchar(255), primary key (id));
create table assignments (attempts_remaining integer not null, function_id integer, has_correct_answer boolean not null, id integer generated by default as identity, status smallint check (status between 0 and 2), user_assigned_id integer, primary key (id));
create table functions (id integer generated by default as identity, result_type smallint check (result_type between 0 and 1), topic_id integer, variables_count integer, hint varchar(255), max_value varchar(255), min_value varchar(255), text varchar(255), primary key (id));
create table groups (id integer generated by default as identity, name varchar(255), primary key (id));
create table marks (assignment_id integer, id integer generated by default as identity, mark integer not null, comment varchar(255), primary key (id));
create table roles (id integer generated by default as identity, name varchar(255) check (name in ('STUDENT','TEACHER','ADMIN')), primary key (id));
create table topics (id integer generated by default as identity, name varchar(255), primary key (id));
create table user_info (group_id integer, id integer not null, first_name varchar(255), last_name varchar(255), primary key (id));
create table user_roles (role_id integer not null, user_id integer not null);
create table users (id integer generated by default as identity, is_approved boolean, email varchar(255), forgot_password_token varchar(255), password varchar(255), refresh_token varchar(255), primary key (id));
alter table if exists answers add constraint FKgjkcqybs0a3akukb2h46s5hmf foreign key (assignment_id) references assignments;
alter table if exists assignments add constraint FK78gs4tabc11nl9vhagk0w38dl foreign key (function_id) references functions;
alter table if exists assignments add constraint FKbwmd4hu3ilm5bnvxwu1hpq857 foreign key (user_assigned_id) references users;
alter table if exists functions add constraint FKkeu713mny1w38bcqwaypk5v0w foreign key (topic_id) references topics;
alter table if exists marks add constraint FKfb1jnc1s7y4idxwfu1mgdarmh foreign key (assignment_id) references assignments;
alter table if exists user_info add constraint FKr4gogbvxc9a4i6gdg6c7lyrma foreign key (group_id) references groups;
alter table if exists user_info add constraint FK84m4x29g16h6ll9apisavaqow foreign key (id) references users;
alter table if exists user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles;
alter table if exists user_roles add constraint FKhfh9dx7w3ubf1co1vdev94g3f foreign key (user_id) references users;
