CREATE TABLE group_students
(
    group_id INTEGER NOT NULL,
    user_id  INTEGER NOT NULL
);

CREATE TABLE group_subjects
(
    group_id   INTEGER NOT NULL,
    subject_id INTEGER NOT NULL
);

CREATE TABLE groups
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255),
    owner_id INTEGER,
    CONSTRAINT pk_groups PRIMARY KEY (id)
);

ALTER TABLE groups
    ADD CONSTRAINT FK_GROUPS_ON_OWNER FOREIGN KEY (owner_id) REFERENCES users (id);

ALTER TABLE group_students
    ADD CONSTRAINT fk_grostu_on_group FOREIGN KEY (group_id) REFERENCES groups (id);

ALTER TABLE group_students
    ADD CONSTRAINT fk_grostu_on_user FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE group_subjects
    ADD CONSTRAINT fk_grosub_on_group FOREIGN KEY (group_id) REFERENCES groups (id);

ALTER TABLE group_subjects
    ADD CONSTRAINT fk_grosub_on_subject FOREIGN KEY (subject_id) REFERENCES subjects (id);