INSERT INTO urls (url, description, method)
VALUES ('/api/assignments', 'Отримати список завдань користувача', 0),
       ('/api/assignments/{userAssignmentId}', 'Отримати завдання користувача за ідентифікатором', 0),
       ('/api/assignments/assign', 'Призначити завдання користувачу', 1),
       ('/api/assignments/{userAssignmentId}/startContinue', 'Розпочати або продовжити виконання завдання', 2),
       ('/api/assignments/{userAssignmentId}/finish', 'Завершити виконання завдання', 2),
       ('/api/assignments/{userAssignmentId}/giveAnswer', 'Надіслати відповідь на завдання', 1),
       ('/api/assignments/{userAssignmentId}/answers', 'Отримати список відповідей користувача на завдання', 0),
       ('/api/fields', 'Отримати список полів для вказаного URL', 0),
       ('/api/assignments/{userAssignmentId}/putMark', 'Оцінити виконане завдання', 2),
       ('/api/assignments/{userAssignmentId}/marks', 'Отримати всі оцінки для завдання', 0),
       ('/api/subjects', 'Отримати список предметів', 0),
       ('/api/universities', 'Отримати список усіх університетів', 0),
       ('/api/urls', 'Отримати список API запитів', 0),
       ('/api/urls/methods', 'Отримати список підтримуваних методів HTTP', 0),
       ('/api/assignmentRestrictions/restrictionTypes', 'Отримати типи обмежень ' ||
                                                        'для завдання', 0),
       ('/api/functions', 'Отримати список функцій', 0),
       ('/api/assignmentRestrictions/setDefaultRestriction', 'Задати обмеження ' ||
                                                             'по замовчуванню для виконання завдання', 2),
       ('/api/permissions', 'Змінити права доступу користувача', 1),
       ('/api/permissions', 'Надати права доступу користувачу', 2),
       ('/api/assignmentRestrictions/setRestriction', 'Задати обмеження для ' ||
                                                      'виконання завдання', 2),
       ('/api/permissions', 'Забрати права доступу користувача', 3),
       ('/api/assignmentRestrictions', 'Отримати поточні обмеження', 0),
       ('/api/universities/{universityId}', 'Отримати університет по ідентифікатору', 0),
       ('/api/universities', 'Додати університет', 1),
       ('/api/universities/{universityId}', 'Оновити університет', 2),
       ('/api/universities/{universityId}', 'Видалити університет', 3),
       ('/api/subjects/{subjectId}', 'Отримати предмет по ідентифікатору', 0),
       ('/api/subjects', 'Додати тему', 1),
       ('/api/subjects/{subjectId}', 'Оновити тему', 2),
       ('/api/subjects/{subjectId}', 'Видалити тему', 3),
       ('/api/functions/{functionId}', 'Отримати функцію по ідентифікатору', 0),
       ('/api/functions', 'Додати функцію', 1),
       ('/api/functions/{functionId}', 'Оновити функцію', 2),
       ('/api/functions/{functionId}', 'Видалити функцію', 3),
       ('/api/assignmentRestrictions/defaultRestrictions',
        'Отримати обмеження для завдань по замовчуванню', 0),
       ('/api/permissions', 'Отримати права користувача', 0),
       ('/api/users', 'Отримати дані про користувачів', 0),
       ('/api/groups', 'Отримати список груп, якими ' ||
                       'володіє поточний користувач', 0),
       ('/api/groups/{groupId}', 'Отримати групу за ідентифікатором', 0),
       ('/api/groups', 'Створити групу', 1),
       ('/api/groups/{groupId}', 'Оновити групу', 2),
       ('/api/groups/{groupId}', 'Видалити групу', 3),
       ('/api/groups/{groupId}/addStudents', 'Додати студентів у групу', 2),
       ('/api/groups/{groupId}/removeStudents', 'Видалити студентів з групи', 2),
       ('/api/groups/{groupId}/addSubjects', 'Додати предмети до групи', 2),
       ('/api/groups/{groupId}/removeSubjects', 'Видалити предмети з групи', 2),
       ('/api/users/{userId}/approve', 'Підтвердити користувача', 2),
       ('/api/users/{userId}/reject', 'Відхилити користувача', 2),
       ('/api/assignments/assignToGroup', 'Призначити завдання групі', 1),
       ('/api/users/{userId}', 'Отримати дані про користувача', 0),
       ('/api/functions/getByAssignmentIds', 'Отримати функції для завдань', 0),
       ('/api/users/createAdmin', 'Створити адміністратора', 1);

INSERT INTO fields (name, label, description, type)
VALUES ('userId', 'Ідентифікатор', 'Унікальний числовий ідентифікатор користувача', 0),
       ('userAssignmentId', 'Ідентифікатор', 'Унікальний числовий ідентифікатор призначення', 0),
       ('name', 'Назва', 'Назва сутності або елемента', 2),
       ('comment', 'Коментар', 'Коментар викладача або системи', 2),
       ('answer', 'Відповідь', 'Текст відповіді користувача', 2),
       ('mark', 'Оцінка', 'Отримана оцінка за завдання', 0),
       ('restrictionType', 'Тип обмеження', 'Тип обмеження для виконання завдання', 4),
       ('attemptsRemaining', 'Залишилось спроб', 'Кількість доступних спроб', 0),
       ('deadline', 'Дедлайн', 'Кінцевий термін виконання завдання', 3),
       ('minutesForAttempt', 'Хвилин для однієї спроби', 'Хвилин для виконання однієї спроби в завданні', 0),
       ('method', 'Метод', 'Тип методу або запиту', 4),
       ('url', 'URL-адреса', 'Веб-адреса ресурсу', 2),
       ('urlId', 'Ідентифікатор', 'Унікальний числовий ідентифікатор запиту', 0),
       ('universityId', 'Ідентифікатор', 'Унікальний числовий ідентифікатор університету', 0),
       ('subjectId', 'Ідентифікатор', 'Унікальний числовий ідентифікатор предмету', 0),
       ('functionId', 'Ідентифікатор', 'Унікальний числовий ідентифікатор функції', 0),
       ('permissionId', 'Ідентифікатор', 'Унікальний числовий ідентифікатор права', 0),
       ('defaultRestrictionId', 'Ідентифікатор',
        'Унікальний числовий ідентифікатор обмеження по замовчуванню', 0),
       ('minValues', 'Мінімальне значення функції', 'Мінімальне значення функції', 1),
       ('maxValues', 'Максимальне значення функції', 'Максимальне значення функції', 1),
       ('text', 'Текст функції', 'Текст функції у форматі: ' ||
                                 'x1^2+x2^3...', 2),
       ('variablesCount', 'Кількість змінних у функції', 'Кількість змінних у функції', 0),
       ('markId', 'Ідентифікатор', 'Унікальний числовий ідентифікатор оцінки', 0),
       ('userIds', 'Ідентифікатор', 'Унікальний числовий ідентифікатор користувача', 0),
       ('subjectIds', 'Ідентифікатор', 'Унікальний числовий ідентифікатор предмету', 0),
       ('groupId', 'Ідентифікатор', 'Унікальний числовий ідентифікатор групи', 0),
       ('roleId', 'Ідентифікатор', 'Унікальний числовий ідентифікатор ролі', 0),
       ('universityIds', 'Ідентифікатор', 'Унікальний числовий ідентифікатор університету', 0),
       ('functionIds', 'Ідентифікатор', 'Унікальний числовий ідентифікатор функції', 0),
       ('userAssignmentIds', 'Ідентифікатор', 'Унікальний числовий ідентифікатор завдання користувача', 0);

insert into url_fields(url_id, field_id, required, multiple)
values ((select id from urls where url = '/api/assignments/assignToGroup'),
        (select id from fields where name = 'groupId'),
        true, false),
       ((select id from urls where url = '/api/assignments/assign'),
        (select id from fields where name = 'subjectIds'),
        true, true),
       ((select id from urls where url = '/api/assignments/{userAssignmentId}/giveAnswer'),
        (select id from fields where name = 'answer'),
        true, false),
       ((select id from urls where url = '/api/fields'),
        (select id from fields where name = 'urlId'),
        true, false),
       ((select id from urls where url = '/api/assignments/{userAssignmentId}/putMark'),
        (select id from fields where name = 'markId'),
        false, false),
       ((select id from urls where url = '/api/assignments/{userAssignmentId}/putMark'),
        (select id from fields where name = 'mark'),
        true, false),
       ((select id from urls where url = '/api/assignments/{userAssignmentId}/putMark'),
        (select id from fields where name = 'comment'),
        true, false),
       ((select id from urls where url = '/api/subjects' and method = 0),
        (select id from fields where name = 'universityId'),
        false, false),
       ((select id from urls where url = '/api/urls'),
        (select id from fields where name = 'url'),
        false, false),
       ((select id from urls where url = '/api/urls'),
        (select id from fields where name = 'method'),
        false, false),
       ((select id from urls where url = '/api/functions' and method = 0),
        (select id from fields where name = 'subjectId'),
        false, false),
       ((select id
         from urls
         where url = '/api/assignmentRestrictions/setDefaultRestriction'
           and method = 2),
        (select id from fields where name = 'restrictionType'),
        true, false),
       ((select id
         from urls
         where url = '/api/assignmentRestrictions/setDefaultRestriction'
           and method = 2),
        (select id from fields where name = 'functionId'),
        false, false),
       ((select id
         from urls
         where url = '/api/assignmentRestrictions/setDefaultRestriction'
           and method = 2),
        (select id from fields where name = 'subjectId'),
        false, false),
       ((select id
         from urls
         where url = '/api/assignmentRestrictions/setDefaultRestriction'
           and method = 2),
        (select id from fields where name = 'universityId'),
        false, false),
       ((select id
         from urls
         where url = '/api/assignmentRestrictions/setDefaultRestriction'
           and method = 2),
        (select id from fields where name = 'attemptsRemaining'),
        false, false),
       ((select id
         from urls
         where url = '/api/assignmentRestrictions/setDefaultRestriction'
           and method = 2),
        (select id from fields where name = 'minutesForAttempt'),
        false, false),
       ((select id
         from urls
         where url = '/api/assignmentRestrictions/setDefaultRestriction'
           and method = 2),
        (select id from fields where name = 'deadline'),
        false, false),
       ((select id from urls where url = '/api/assignmentRestrictions/setRestriction'),
        (select id from fields where name = 'restrictionType'),
        true, false),
       ((select id from urls where url = '/api/assignmentRestrictions/setRestriction'),
        (select id from fields where name = 'functionId'),
        false, false),
       ((select id from urls where url = '/api/assignmentRestrictions/setRestriction'),
        (select id from fields where name = 'subjectId'),
        false, false),
       ((select id from urls where url = '/api/assignmentRestrictions/setRestriction'),
        (select id from fields where name = 'universityId'),
        false, false),
       ((select id from urls where url = '/api/assignmentRestrictions/setRestriction'),
        (select id from fields where name = 'userAssignmentId'),
        false, false),
       ((select id from urls where url = '/api/assignmentRestrictions/setRestriction'),
        (select id from fields where name = 'attemptsRemaining'),
        false, false),
       ((select id from urls where url = '/api/assignmentRestrictions/setRestriction'),
        (select id from fields where name = 'minutesForAttempt'),
        false, false),
       ((select id from urls where url = '/api/assignmentRestrictions/setRestriction'),
        (select id from fields where name = 'deadline'),
        false, false),
       ((select id from urls where url = '/api/assignmentRestrictions' and method = 0),
        (select id from fields where name = 'userAssignmentId'),
        true, false),
       ((select id from urls where url = '/api/users' and method = 0),
        (select id from fields where name = 'roleId'),
        false, false),
       ((select id from urls where url = '/api/functions/getByAssignmentIds' and method = 0),
        (select id from fields where name = 'userAssignmentIds'),
        false, true);

insert into url_fields(url_id, field_id, required, multiple)
values ((select id from urls where url = '/api/users/createAdmin'),
        (select id from fields where name = 'firstName'),
        true, false),
       ((select id from urls where url = '/api/users/createAdmin'),
        (select id from fields where name = 'lastName'),
        true, false),
       ((select id from urls where url = '/api/users/createAdmin'),
        (select id from fields where name = 'email'),
        true, false),
       ((select id from urls where url = '/api/users/createAdmin'),
        (select id from fields where name = 'password'),
        true, false),
       ((select id from urls where url = '/api/permissions' and method in (1, 2, 3)),
        (select id from fields where name = 'userId'),
        true, false),
       ((select id from urls where url = '/api/permissions' and method in (1, 2, 3)),
        (select id from fields where name = 'universityIds'),
        false, true),
       ((select id from urls where url = '/api/permissions' and method in (1, 2, 3)),
        (select id from fields where name = 'subjectIds'),
        false, true),
       ((select id from urls where url = '/api/permissions' and method in (1, 2, 3)),
        (select id from fields where name = 'functionIds'),
        false, true),
       ((select id from urls where url = '/api/permissions' and method in (1, 2, 3)),
        (select id from fields where name = 'userAssignmentIds'),
        false, true),
       ((select id from urls where url = '/api/universities' and method = 1),
        (select id from fields where name = 'name'),
        true, false),
       ((select id from urls where url = '/api/universities/{universityId}' and method = 2),
        (select id from fields where name = 'name'),
        false, false),
       ((select id from urls where url = '/api/subjects' and method = 1),
        (select id from fields where name = 'name'),
        true, false),
       ((select id from urls where url = '/api/subjects' and method = 1),
        (select id from fields where name = 'universityId'),
        true, false),
       ((select id from urls where url = '/api/subjects/{subjectId}' and method = 2),
        (select id from fields where name = 'name'),
        false, false),
       ((select id from urls where url = '/api/subjects/{subjectId}' and method = 2),
        (select id from fields where name = 'universityId'),
        false, false),
       ((select id from urls where url = '/api/functions' and method = 1),
        (select id from fields where name = 'text'),
        true, false),
       ((select id from urls where url = '/api/functions' and method = 1),
        (select id from fields where name = 'variablesCount'),
        true, false),
       ((select id from urls where url = '/api/functions' and method = 1),
        (select id from fields where name = 'minValues'),
        true, true),
       ((select id from urls where url = '/api/functions' and method = 1),
        (select id from fields where name = 'maxValues'),
        true, true),
       ((select id from urls where url = '/api/functions' and method = 1),
        (select id from fields where name = 'subjectId'),
        true, false),
       ((select id from urls where url = '/api/functions/{functionId}' and method = 2),
        (select id from fields where name = 'text'),
        false, false),
       ((select id from urls where url = '/api/functions/{functionId}' and method = 2),
        (select id from fields where name = 'variablesCount'),
        false, false),
       ((select id from urls where url = '/api/functions/{functionId}' and method = 2),
        (select id from fields where name = 'minValues'),
        false, true),
       ((select id from urls where url = '/api/functions/{functionId}' and method = 2),
        (select id from fields where name = 'maxValues'),
        false, true),
       ((select id from urls where url = '/api/functions/{functionId}' and method = 2),
        (select id from fields where name = 'subjectId'),
        false, false),
       ((select id from urls where url = '/api/assignmentRestrictions/defaultRestrictions'),
        (select id from fields where name = 'functionId'),
        false, false),
       ((select id from urls where url = '/api/assignmentRestrictions/defaultRestrictions'),
        (select id from fields where name = 'subjectId'),
        false, false),
       ((select id from urls where url = '/api/assignmentRestrictions/defaultRestrictions'),
        (select id from fields where name = 'universityId'),
        false, false),
       ((select id from urls where url = '/api/permissions'),
        (select id from fields where name = 'userId'),
        false, false),
       ((select id from urls where url = '/api/groups' and method = 1),
        (select id from fields where name = 'name'),
        true, false),
       ((select id from urls where url = '/api/groups/{groupId}' and method = 2),
        (select id from fields where name = 'name'),
        false, false),
       ((select id from urls where url = '/api/groups/{groupId}/addStudents'),
        (select id from fields where name = 'userIds'),
        false, true),
       ((select id from urls where url = '/api/groups/{groupId}/removeStudents'),
        (select id from fields where name = 'userIds'),
        false, true),
       ((select id from urls where url = '/api/groups/{groupId}/addSubjects'),
        (select id from fields where name = 'subjectIds'),
        false, true),
       ((select id from urls where url = '/api/groups/{groupId}/removeSubjects'),
        (select id from fields where name = 'subjectIds'),
        false, true),
       ((select id from urls where url = '/api/groups' and method = 1),
        (select id from fields where name = 'subjectIds'),
        true, true),
       ((select id from urls where url = '/api/groups' and method = 1),
        (select id from fields where name = 'userIds'),
        true, true),
       ((select id from urls where url = '/api/groups/{groupId}' and method = 2),
        (select id from fields where name = 'subjectIds'),
        false, true),
       ((select id from urls where url = '/api/groups/{groupId}' and method = 2),
        (select id from fields where name = 'userIds'),
        false, true);