ALTER TABLE functions
    DROP CONSTRAINT fkkeu713mny1w38bcqwaypk5v0w;

ALTER TABLE user_info
    DROP CONSTRAINT fkr4gogbvxc9a4i6gdg6c7lyrma;

CREATE TABLE subjects
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_subjects PRIMARY KEY (id)
);

ALTER TABLE functions
    ADD subject_id INTEGER;

ALTER TABLE functions
    ADD CONSTRAINT FK_FUNCTIONS_ON_SUBJECT FOREIGN KEY (subject_id) REFERENCES subjects (id);

DROP TABLE groups CASCADE;

DROP TABLE topics CASCADE;

ALTER TABLE user_info
    DROP COLUMN group_id;

ALTER TABLE functions
    DROP COLUMN topic_id;