ALTER TABLE assignments
    DROP CONSTRAINT fk78gs4tabc11nl9vhagk0w38dl;

ALTER TABLE assignments
    DROP CONSTRAINT fkbwmd4hu3ilm5bnvxwu1hpq857;

ALTER TABLE marks
    DROP CONSTRAINT fkfb1jnc1s7y4idxwfu1mgdarmh;

ALTER TABLE answers
    DROP CONSTRAINT fkgjkcqybs0a3akukb2h46s5hmf;

CREATE TABLE default_assignment_restrictions
(
    id                          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    university_id               INTEGER,
    subject_id                  INTEGER,
    function_id                 INTEGER,
    assignment_restriction_type SMALLINT,
    attempts_remaining          INTEGER                                  NOT NULL,
    minutes_for_attempt         INTEGER                                  NOT NULL,
    minutes_to_deadline         INTEGER                                  NOT NULL,
    CONSTRAINT pk_default_assignment_restrictions PRIMARY KEY (id)
);

CREATE TABLE fields
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    label       VARCHAR(255),
    description VARCHAR(255),
    type        SMALLINT,
    required    BOOLEAN                                  NOT NULL,
    query_param BOOLEAN,
    body_param  BOOLEAN,
    CONSTRAINT pk_fields PRIMARY KEY (id)
);

CREATE TABLE universities
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255),
    CONSTRAINT pk_universities PRIMARY KEY (id)
);

CREATE TABLE url_fields
(
    field_id INTEGER NOT NULL,
    url_id   INTEGER NOT NULL
);

CREATE TABLE urls
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    url         VARCHAR(255),
    description VARCHAR(255),
    method      SMALLINT,
    CONSTRAINT pk_urls PRIMARY KEY (id)
);

CREATE TABLE user_assignments
(
    id                  INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    function_id         INTEGER,
    assignment_id       INTEGER,
    user_id             INTEGER,
    status              SMALLINT,
    restriction_type    SMALLINT,
    has_correct_answer  BOOLEAN                                  NOT NULL,
    attempts_remaining  INTEGER                                  NOT NULL,
    last_attempt_time   TIMESTAMP WITHOUT TIME ZONE,
    minutes_for_attempt INTEGER                                  NOT NULL,
    deadline            TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_user_assignments PRIMARY KEY (id)
);

CREATE TABLE user_permissions
(
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id            INTEGER,
    university_id      INTEGER,
    subject_id         INTEGER,
    function_id        INTEGER,
    user_assignment_id INTEGER,
    CONSTRAINT pk_user_permissions PRIMARY KEY (id)
);

ALTER TABLE user_info
    ADD api_key VARCHAR(255);

ALTER TABLE assignments
    ADD function_result_type SMALLINT;

ALTER TABLE assignments
    ADD text VARCHAR(255);

ALTER TABLE functions
    ADD max_values VARCHAR(255);

ALTER TABLE functions
    ADD min_values VARCHAR(255);

ALTER TABLE subjects
    ADD university_id INTEGER;

ALTER TABLE answers
    ADD user_assignment_id INTEGER;

ALTER TABLE marks
    ADD user_assignment_id INTEGER;

ALTER TABLE answers
    ADD CONSTRAINT FK_ANSWERS_ON_USER_ASSIGNMENT FOREIGN KEY (user_assignment_id) REFERENCES user_assignments (id);

ALTER TABLE default_assignment_restrictions
    ADD CONSTRAINT FK_DEFAULT_ASSIGNMENT_RESTRICTIONS_ON_FUNCTION FOREIGN KEY (function_id) REFERENCES functions (id);

ALTER TABLE default_assignment_restrictions
    ADD CONSTRAINT FK_DEFAULT_ASSIGNMENT_RESTRICTIONS_ON_SUBJECT FOREIGN KEY (subject_id) REFERENCES subjects (id);

ALTER TABLE default_assignment_restrictions
    ADD CONSTRAINT FK_DEFAULT_ASSIGNMENT_RESTRICTIONS_ON_UNIVERSITY FOREIGN KEY (university_id) REFERENCES universities (id);

ALTER TABLE marks
    ADD CONSTRAINT FK_MARKS_ON_USER_ASSIGNMENT FOREIGN KEY (user_assignment_id) REFERENCES user_assignments (id);

ALTER TABLE subjects
    ADD CONSTRAINT FK_SUBJECTS_ON_UNIVERSITY FOREIGN KEY (university_id) REFERENCES universities (id);

ALTER TABLE user_assignments
    ADD CONSTRAINT FK_USER_ASSIGNMENTS_ON_ASSIGNMENT FOREIGN KEY (assignment_id) REFERENCES assignments (id);

ALTER TABLE user_assignments
    ADD CONSTRAINT FK_USER_ASSIGNMENTS_ON_FUNCTION FOREIGN KEY (function_id) REFERENCES functions (id);

ALTER TABLE user_assignments
    ADD CONSTRAINT FK_USER_ASSIGNMENTS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE user_permissions
    ADD CONSTRAINT FK_USER_PERMISSIONS_ON_FUNCTION FOREIGN KEY (function_id) REFERENCES functions (id);

ALTER TABLE user_permissions
    ADD CONSTRAINT FK_USER_PERMISSIONS_ON_SUBJECT FOREIGN KEY (subject_id) REFERENCES subjects (id);

ALTER TABLE user_permissions
    ADD CONSTRAINT FK_USER_PERMISSIONS_ON_UNIVERSITY FOREIGN KEY (university_id) REFERENCES universities (id);

ALTER TABLE user_permissions
    ADD CONSTRAINT FK_USER_PERMISSIONS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE user_permissions
    ADD CONSTRAINT FK_USER_PERMISSIONS_ON_USER_ASSIGNMENT FOREIGN KEY (user_assignment_id) REFERENCES user_assignments (id);

ALTER TABLE url_fields
    ADD CONSTRAINT fk_urlfie_on_field FOREIGN KEY (field_id) REFERENCES fields (id);

ALTER TABLE url_fields
    ADD CONSTRAINT fk_urlfie_on_url FOREIGN KEY (url_id) REFERENCES urls (id);

ALTER TABLE answers
    DROP COLUMN assignment_id;

ALTER TABLE marks
    DROP COLUMN assignment_id;

ALTER TABLE assignments
    DROP COLUMN attempts_remaining;

ALTER TABLE assignments
    DROP COLUMN function_id;

ALTER TABLE assignments
    DROP COLUMN has_correct_answer;

ALTER TABLE assignments
    DROP COLUMN status;

ALTER TABLE assignments
    DROP COLUMN user_assigned_id;

ALTER TABLE functions
    DROP COLUMN hint;

ALTER TABLE functions
    DROP COLUMN max_value;

ALTER TABLE functions
    DROP COLUMN min_value;

ALTER TABLE functions
    DROP COLUMN result_type;