CREATE TABLE maze_points
(
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    x               INTEGER                                  NOT NULL,
    y               INTEGER                                  NOT NULL,
    maze_point_type SMALLINT,
    maze_id         INTEGER,
    CONSTRAINT pk_maze_points PRIMARY KEY (id)
);

CREATE TABLE mazes
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255),
    width         INTEGER                                  NOT NULL,
    height        INTEGER                                  NOT NULL,
    university_id INTEGER,
    CONSTRAINT pk_mazes PRIMARY KEY (id)
);

ALTER TABLE assignments
    ADD assignment_type SMALLINT;

ALTER TABLE answers
    ADD is_wall BOOLEAN;

ALTER TABLE default_assignment_restrictions
    ADD maze_id INTEGER;

ALTER TABLE user_assignments
    ADD maze_id INTEGER;

ALTER TABLE user_permissions
    ADD maze_id INTEGER;

ALTER TABLE default_assignment_restrictions
    ADD CONSTRAINT FK_DEFAULT_ASSIGNMENT_RESTRICTIONS_ON_MAZE FOREIGN KEY (maze_id) REFERENCES mazes (id);

ALTER TABLE mazes
    ADD CONSTRAINT FK_MAZES_ON_UNIVERSITY FOREIGN KEY (university_id) REFERENCES universities (id);

ALTER TABLE maze_points
    ADD CONSTRAINT FK_MAZE_POINTS_ON_MAZE FOREIGN KEY (maze_id) REFERENCES mazes (id);

ALTER TABLE user_assignments
    ADD CONSTRAINT FK_USER_ASSIGNMENTS_ON_MAZE FOREIGN KEY (maze_id) REFERENCES mazes (id);

ALTER TABLE user_permissions
    ADD CONSTRAINT FK_USER_PERMISSIONS_ON_MAZE FOREIGN KEY (maze_id) REFERENCES mazes (id);

ALTER TABLE assignments
    DROP COLUMN function_result_type;