server:
  port: 8080
spring:
  application:
    name: APIApplication
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      javax:
        persistence:
          schema-generation:
            scripts:
              action: create
              create-target: src/main/resources/db/migration/V1__init.sql
            create-source: metadata
  flyway:
    baseline-on-migrate: true
    enabled: true
    url: ${SPRING_DATASOURCE_URL}
    user: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    baseline-version: 0
    validate-on-migrate: false

email_service:
  api-key: ${SENDGRID_API_KEY}
  from-email: ${FROM_EMAIL}
  frontend-url: ${FRONTEND_URL}

app:
  jwt:
    access-token-secret: ${ACCESS_TOKEN_SECRET}
    refresh-token-secret: ${REFRESH_TOKEN_SECRET}
    expiration-ms: 3600000
    refresh-expiration-ms: 86400000